//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCTest10_15.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             101
#define IDD_SOCK_DIALOG                 102
#define IDD_DIALOG_IRI                  104
#define IDD_CONTROLVIEW                 103
#define IDP_SOCKETS_INIT_FAILED         105
#define IDR_MAINFRAME                   128
#define IDR_MFCTest10_15TYPE            129
#define IDD_CONTRLDLG                   131
#define IDD_BACK_RING                   142
#define IDI_ICON1                       148
#define IDD_DIALOG_CN_COMM              150
#define IDD_VC6_DIALOG                  151
#define IDD_DIALOG_DCB                  152
#define IDD_DIALOG_TIMEOUTS             153
#define IDI_ICON_OFF                    154
#define IDI_ICON_ON                     155
#define IDD_DIALOG_PROPERTIES           156
#define IDD_SOCK_DIALOG1                157
#define IDC_EDIT1                       1000
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_EDIT2                       1003
#define IDC_EDIT3                       1004
#define IDC_BUTTON3                     1005
#define IDC_BUTTON4                     1006
#define IDC_EDIT4                       1007
#define IDC_COMBO1                      1008
#define IDC_BUTTON5                     1009
#define IDC_BUTTON6                     1010
#define IDC_BUTFUWEI                    1011
#define IDC_SLIDER1                     1012
#define IDC_SLIDER2                     1015
#define IDC_SLIDER3                     1016
#define IDC_RADIO1                      1018
#define IDC_RADIO2                      1019
#define IDC_RADIO3                      1020
#define IDC_STATICTip                   1022
#define IDC_STATICExposure              1023
#define IDC_BUTSAVE                     1024
#define IDC_RADIO6                      1030
#define IDC_RADIO7                      1031
#define IDC_RADIO4                      1032
#define IDC_RADIO5                      1033
#define IDC_RADIO8                      1034
#define IDC_RADIO9                      1035
#define IDC_RADIO10                     1036
#define IDC_RADIO11                     1037
#define IDC_CHK1                        1039
#define IDC_CHK3                        1040
#define IDC_CHK2                        1041
#define IDC_CHECK4                      1042
#define IDC_CHK4                        1042
#define IDC_ESERVNAME                   1100
#define IDC_ESERVPORT                   1101
#define IDC_BCONNECT                    1102
#define IDC_BCLOSE                      1103
#define IDC_STATICMSG                   1104
#define IDC_EMSG                        1105
#define IDC_BSEND                       1106
#define IDC_LSENT                       1108
#define IDC_LRECVD                      1109
#define IDC_EFCH                        1110
#define IDC_ECHN                        1111
#define IDC_EGAIN                       1113
#define IDC_EFR                         1114
#define IDC_BCJ                         1115
#define IDC_BCLS                        1116
#define IDC_BUTTON_NEW_INSTANCE         1200
#define IDC_TAB                         1201
#define IDC_BUTTON_FREE_INSTANCE        1202
#define IDC_EDIT_RX                     1203
#define IDC_COMBO_COM_PORT              1204
#define IDC_COMBO_PARITY                1205
#define IDC_COMBO_BAUDRATE              1206
#define IDC_COMBO_BITSSIZE              1207
#define IDC_COMBO_STOPBITS              1208
#define IDC_BUTTON_OPEN                 1209
#define IDC_BUTTON_CLEAR_RX             1210
#define IDC_EDIT_TX                     1211
#define IDC_BUTTON_SEND                 1212
#define IDC_BUTTON_CLEAR_TX             1213
#define IDC_CHECK_TX_HEX                1214
#define IDC_EDIT_CYCLE                  1215
#define IDC_CHECK_AUTO_SEND             1216
#define IDC_EDIT_RX_COUNT               1217
#define IDC_EDIT_TX_COUNT               1218
#define IDC_CHECK_EN_THREAD             1219
#define IDC_CHECK_EN_OVERLAPPED         1220
#define IDC_CHECK_EN_TX_BUFFER          1221
#define IDC_CHECK_EN_RX_BUFFER          1222
#define IDC_CHECK_EN_TX_THREAD          1223
#define IDC_CHECK_EN_RX_THREAD          1224
#define IDC_COMBO_FLOW_CTRL             1225
#define IDC_CHECK_RX_HEX                1226
#define IDC_EDIT_RX_QUEUE               1227
#define IDC_EDIT_TX_QUEUE               1228
#define IDC_BUTTON_RESET                1229
#define IDC_EDIT_RX_BUFFER              1230
#define IDC_EDIT_DCBlength              1231
#define IDC_EDIT_TX_BUFFER              1231
#define IDC_EDIT_BaudRate               1232
#define IDC_EDIT_fBinary                1233
#define IDC_EDIT_fParity                1234
#define IDC_EDIT_fOutxCtsFlow           1235
#define IDC_EDIT_fDtrControl            1236
#define IDC_EDIT_fDsrSensitivity        1237
#define IDC_EDIT_fTXContinueOnXoff      1238
#define IDC_EDIT_fOutX                  1239
#define IDC_EDIT_fInX                   1240
#define IDC_EDIT_fErrorChar             1241
#define IDC_EDIT_fNull                  1242
#define IDC_EDIT_fRtsControl            1243
#define IDC_EDIT_fAbortOnError          1244
#define IDC_EDIT_fDummy2                1245
#define IDC_EDIT_wReserved              1246
#define IDC_EDIT_XonLim                 1247
#define IDC_EDIT_XoffLim                1248
#define IDC_EDIT_ByteSize               1249
#define IDC_BUTTON_SET                  1250
#define IDC_EDIT_dwCallSetupFailTimer   1250
#define IDC_EDIT_Parity                 1251
#define IDC_EDIT_StopBits               1252
#define IDC_EDIT_XonChar                1253
#define IDC_EDIT_XoffChar               1254
#define IDC_EDIT_dwInactivityTimeout    1255
#define IDC_EDIT_dwSpeakerVolume        1256
#define IDC_EDIT_dwSpeakerMode          1257
#define IDC_EDIT_dwModemOptions         1258
#define IDC_EDIT_ErrorChar              1267
#define IDC_EDIT_EofChar                1268
#define IDC_EDIT_EvtChar                1269
#define IDC_EDIT_wReserved1             1270
#define IDC_EDIT_dwMaxDTERate           1271
#define IDC_EDIT_dwMaxDCERate           1272
#define IDC_EDIT_dwModemVersionSize     1273
#define IDC_BUTTON_DCB                  1289
#define IDC_BUTTON_SEND_FILE            1290
#define IDC_EDIT_FILE_FOR_SEND          1291
#define IDC_BUTTON_BROWER_TX            1292
#define IDC_BUTTON_LOAD_FILE            1293
#define IDC_CHECK_DTR                   1294
#define IDC_CHECK_BREAK                 1295
#define IDC_CHECK_RTS                   1296
#define IDC_CHECK_XON                   1297
#define IDC_CHECK_RLSD                  1298
#define IDC_CHECK_RING                  1299
#define IDC_CHECK_DSR                   1300
#define IDC_CHECK_CTS                   1301
#define IDC_BUTTON_BROWER_RX            1303
#define IDC_BUTTON_TIMEOUTS             1304
#define IDC_BUTTON_PROPERTIES           1305
#define IDC_EDIT_RIT                    1306
#define IDC_EDIT_FILE_FOR_RECV          1306
#define IDC_EDIT_RTTM                   1307
#define IDC_EDIT_RTTC                   1308
#define IDC_EDIT_WTTM                   1309
#define IDC_EDIT_WTTC                   1310
#define IDC_STATIC_LAMP                 1316
#define IDC_EDIT_wPacketLength          1317
#define IDC_EDIT_wPacketVersion         1318
#define IDC_EDIT_dwServiceMask          1319
#define IDC_EDIT_dwMaxTxQueue           1321
#define IDC_EDIT_dwMaxRxQueue           1322
#define IDC_EDIT_dwMaxBaud              1323
#define IDC_EDIT_dwProvSubType          1324
#define IDC_EDIT_dwProvCapabilities     1325
#define IDC_EDIT_dwSettableParams       1326
#define IDC_EDIT_dwSettableBaud         1327
#define IDC_EDIT_wSettableData          1328
#define IDC_EDIT_wSettableStopParity    1329
#define IDC_EDIT_dwCurrentTxQueue       1330
#define IDC_EDIT_dwCurrentRxQueue       1331
#define IDC_EDIT_dwProvSpec1            1332
#define IDC_EDIT_dwProvSpec2            1333
#define IDC_EDIT_dwRequiredSize         1334
#define IDC_EDIT_dwDevSpecificOffset    1335
#define IDC_EDIT_dwDevSpecificSize      1336
#define IDC_EDIT_dwModemProviderVersion 1337
#define IDC_EDIT_dwModemManufacturerOffset 1338
#define IDC_EDIT_dwModemManufacturerSize 1339
#define IDC_EDIT_dwModemModelOffset     1340
#define IDC_EDIT_dwModemModelSize       1341
#define IDC_EDIT_dwModemVersionOffset   1342
#define IDC_EDIT_dwDialOptions          1343
#define IDC_CHECK_DISP                  1345
#define IDC_CHECK_SAVE                  1346
#define IDC_STATIC_RX                   1348
#define IDC_STATIC_TX                   1349
#define IDC_STATIC_MAIL                 1351
#define IDC_STATIC_BLOG1                1352
#define IDC_STATIC_BLOG2                1353
#define IDC_EDIT_IRI                    1401
#define ID_32771                        32771
#define ID_APP_ACCELERATION             32772
#define ID_32773                        32773
#define ID_GPS                          32774
#define ID_32775                        32775
#define ID_menu_iri                     32776
#define IDD_BACK_GROUND                 59396

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        157
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1402
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
